name: New line at the end of files
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  build:
    name: New line
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - uses: Logerfo/newline-action@release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
